[versions]
kotlin = "2.1.0"
intellijPlugin = "1.17.4"
plugin-version = "1.0.0"
# 常用工具库
gson = "2.10.1"
commonsLang3 = "3.14.0"
jackson = "2.12.2"
okhttp = "4.12.0"
guice = "5.1.0"
[libraries]
# --- 核心工具 ---
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
commonsLang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij", version.ref = "intellijPlugin" }